name: Pages

on:
  workflow_dispatch:
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '16'
        
    - name: Install dependencies
      run: |
        npm install
        npm install -g @angular/cli
      
    - name: Build
      run: ng build
              
    - name: Deploy
      run: |
         ng add angular-cli-ghpages
         ng deploy --base-href=https://Malavika1113.github.io/Angular-HelloWorld/
